### ISSUE TITLE
Deploying triggers with CF

### ISSUE THREAD

**Issue by 752101** [aws-quickstart/lambda-copyzips#2]
I do not find any reference here for deploying Lambda triggers using Cloudformation along with Lambda functions, can you please some example for that.

**Comment by mouhannadali** [comment]
I had a similar situation and to solve that I had to use CustomResource

```
Resources:
  Primerinvoke:
    Type: 'AWS::CloudFormation::CustomResource'
    Properties:
      ServiceToken: !GetAtt 
        - LambdaFunctionResourceName
        - Arn
      Region: !Ref 'AWS::Region'
      OtherParameters: Vlaues...
```


and in the lambda function, u need to handle the event and return a response. otherwise, the cloud formation stake will keep running forever (until the timeout). in lambda Go u can do something like this:
```
func main() {
	lambda.Start(cfn.LambdaWrap(handler))
}

func handler(ctx context.Context, event cfn.Event) (physicalResourceID string, data map[string]interface{}, err error) {
	if err != nil {
		return "Could not ....", map[string]interface{}{}, err
	}

	return "perfect", nil, err
}
```
